export const books = [
    {
        imageSrc: 'https://via.placeholder.com/100',
        username: 'User 1',
        userAvatarSrc: 'https://via.placeholder.com/20',
        name: 'Book 1',
        author: 'Author 1',
        price: 2.99,
    },
    {
        imageSrc: 'https://via.placeholder.com/100',
        username: 'User 2',
        userAvatarSrc: 'https://via.placeholder.com/20',
        name: 'Book 2',
        author: 'Author 2',
        price: 14,
    },
    {
        imageSrc: 'https://via.placeholder.com/100',
        username: 'User 3',
        userAvatarSrc: 'https://via.placeholder.com/20',
        name: 'Book 3',
        author: 'Author 3',
    },
    {
        imageSrc: 'https://via.placeholder.com/100',
        username: 'User 4',
        userAvatarSrc: 'https://via.placeholder.com/20',
        name: 'Book 4',
        author: 'Author 4',
        price: 4.56,
    },
    {
        imageSrc: 'https://via.placeholder.com/100',
        username: 'User 5',
        userAvatarSrc: 'https://via.placeholder.com/20',
        name: 'Book 5',
        author: 'Author 5',
        price: 8.99,
    },
]